/* ═══════════ 多平台资源包导出 ═══════════ */
"use strict";

const EXPORT_OPTS = { platforms: new Set(["android", "ios", "web", "macos", "windows"]), formats: new Set(["png"]), customSizes: [] };

async function canvasToBytes(canvas, type = "image/png", quality) {
  const blob = await new Promise(r => canvas.toBlob(r, type, quality));
  return new Uint8Array(await blob.arrayBuffer());
}

/* 渲染指定配置到 PNG 字节 */
async function renderPng(size, opts, type = "image/png", quality) {
  const cv = makeCanvas(size);
  await renderIcon(cv.getContext("2d"), size, opts);
  return canvasToBytes(cv, type, quality);
}

const webShape = () => ({ shape: state.mask.type, radius: state.mask.radius, customPath: state.mask.custom, pad: state.mask.pad / 100 });

/* ── 平台规格 ── */
const ANDROID_DENSITIES = [["mdpi", 48], ["hdpi", 72], ["xhdpi", 96], ["xxhdpi", 144], ["xxxhdpi", 192]];
const ANDROID_FG = [["mdpi", 108], ["hdpi", 162], ["xhdpi", 216], ["xxhdpi", 324], ["xxxhdpi", 432]];
const IOS_ICONS = [
  ["Icon-20.png", 20, "20x20", "1x", "ipad"], ["Icon-20@2x.png", 40, "20x20", "2x", "iphone"],
  ["Icon-20@3x.png", 60, "20x20", "3x", "iphone"], ["Icon-29.png", 29, "29x29", "1x", "ipad"],
  ["Icon-29@2x.png", 58, "29x29", "2x", "iphone"], ["Icon-29@3x.png", 87, "29x29", "3x", "iphone"],
  ["Icon-40.png", 40, "40x40", "1x", "ipad"], ["Icon-40@2x.png", 80, "40x40", "2x", "iphone"],
  ["Icon-40@3x.png", 120, "40x40", "3x", "iphone"], ["Icon-60@2x.png", 120, "60x60", "2x", "iphone"],
  ["Icon-60@3x.png", 180, "60x60", "3x", "iphone"], ["Icon-76.png", 76, "76x76", "1x", "ipad"],
  ["Icon-76@2x.png", 152, "76x76", "2x", "ipad"], ["Icon-83.5@2x.png", 167, "83.5x83.5", "2x", "ipad"],
  ["Icon-1024.png", 1024, "1024x1024", "1x", "ios-marketing"],
];

function iosContentsJson() {
  return JSON.stringify({
    images: IOS_ICONS.map(([fn, , size, scale, idiom]) => ({ filename: fn, idiom, scale, size })),
    info: { author: "qm-icon", version: 1 },
  }, null, 2);
}

function adaptiveXml(monochrome) {
  return `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>${monochrome ? `
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>` : ""}
</adaptive-icon>`;
}

function webManifest() {
  return JSON.stringify({
    name: state.name, short_name: state.name,
    icons: [
      { src: "/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512x512.png", sizes: "512x512", type: "image/png" },
      { src: "/icon-maskable-512x512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    theme_color: state.bg.type === "none" ? "#ffffff" : state.bg.c1,
    background_color: "#ffffff", display: "standalone",
  }, null, 2);
}

function webSnippet() {
  return `<!-- Generated by 该影 icon -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="${state.bg.type === "none" ? "#ffffff" : state.bg.c1}">
<meta property="og:image" content="/og-image.png">`;
}

/* SVG 矢量导出（文字 / 内置图标 / 在线图标 / SVG 粘贴时为精确矢量，其余为嵌入位图） */
async function buildSvg(size = 512) {
  const st = state;
  const defs = [], body = [];
  // 背景
  if (st.layers.bg && st.bg.type !== "none") {
    if (st.bg.type === "solid") body.push(`<rect width="${size}" height="${size}" fill="${st.bg.c1}"/>`);
    else {
      const a = ((st.bg.angle - 90) * Math.PI) / 180;
      const x2 = 50 + Math.cos(a) * 50, y2 = 50 + Math.sin(a) * 50;
      if (st.bg.type === "radial")
        defs.push(`<radialGradient id="bgg"><stop offset="0" stop-color="${st.bg.c1}"/><stop offset="1" stop-color="${st.bg.c2}"/></radialGradient>`);
      else
        defs.push(`<linearGradient id="bgg" x1="${100 - x2}%" y1="${100 - y2}%" x2="${x2}%" y2="${y2}%"><stop offset="0" stop-color="${st.bg.c1}"/><stop offset="1" stop-color="${st.bg.c2}"/></linearGradient>`);
      body.push(`<rect width="${size}" height="${size}" fill="url(#bgg)"/>`);
    }
  }
  // 前景
  const box = size * st.fg.scale;
  const tx = size / 2 + (st.fg.dx / 100) * size, ty = size / 2 + (st.fg.dy / 100) * size;
  const tf = `translate(${tx} ${ty}) rotate(${st.fg.rot})${st.fg.flip ? " scale(-1 1)" : ""}`;
  const fillRef = st.tint.mode === "gradient" ? "url(#fgg)" : st.tint.c1;
  if (st.tint.mode === "gradient")
    defs.push(`<linearGradient id="fgg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${st.tint.c1}"/><stop offset="1" stop-color="${st.tint.c2}"/></linearGradient>`);

  if ((st.source === "clipart" || st.source === "brand") && !st.clipart.svg) {
    const icon = BUILTIN_ICONS.find(i => i.n === st.clipart.id) || BUILTIN_ICONS[0];
    body.push(`<g transform="${tf}"><path transform="translate(${-box / 2} ${-box / 2}) scale(${box / 24})" d="${icon.d}" fill="${fillRef}"${icon.fr ? ` fill-rule="${icon.fr}"` : ""}/></g>`);
  } else if ((st.source === "clipart" || st.source === "brand") && st.clipart.svg) {
    const vb = st.clipart.vb || "0 0 24 24";
    const [, , vw] = vb.split(/\s+/).map(Number);
    const inner = st.tint.mode === "original" ? st.clipart.svg : st.clipart.svg.replace(/currentColor/g, fillRef);
    body.push(`<g transform="${tf}"><g transform="translate(${-box / 2} ${-box / 2}) scale(${box / (vw || 24)})">${inner}</g></g>`);
  } else if (st.source === "text") {
    const lines = (st.text.value || "A").split("\n");
    const fs = box * 0.7 / Math.max(1, lines.length * 0.9);
    body.push(`<g transform="${tf}">` + lines.map((l, i) =>
      `<text x="0" y="${(i - (lines.length - 1) / 2) * fs * st.text.lh}" font-family="${st.text.font}" font-weight="${st.text.weight}" font-size="${fs}" fill="${fillRef}" text-anchor="middle" dominant-baseline="central">${l.replace(/&/g, "&amp;").replace(/</g, "&lt;")}</text>`).join("") + "</g>");
  } else {
    // 位图内容：嵌入渲染结果（含图像调整）
    const cv = makeCanvas(Math.round(box) || 2);
    const content = await drawContent(st, cv.width);
    applyAdjustments(content, st.adjust);
    body.push(`<g transform="${tf}"><image href="${content.toDataURL()}" x="${-box / 2}" y="${-box / 2}" width="${box}" height="${box}"/></g>`);
  }
  // 徽章（圆点样式带内容，与画布渲染对齐）
  if (st.layers.badge && st.badge.on) {
    const b = st.badge;
    const esc = s => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");
    const fsz = size * 0.1 * (b.size / 0.3);
    if (b.style === "bar") {
      const h = size * 0.2 * (b.size / 0.3);
      body.push(`<rect y="${size - h}" width="${size}" height="${h}" fill="${b.bg}"/>`);
      body.push(`<text x="${size / 2}" y="${size - h / 2 + fsz * 0.05}" font-family="Inter,'Noto Sans SC',sans-serif" font-weight="800" font-size="${fsz}" fill="${b.fg}" text-anchor="middle" dominant-baseline="central">${esc(b.text)}</text>`);
    } else if (b.style === "dot") {
      const r = size * 0.12 * (b.size / 0.3);
      const [bx, by] = { tl: [r * 1.2, r * 1.2], tr: [size - r * 1.2, r * 1.2], bl: [r * 1.2, size - r * 1.2], br: [size - r * 1.2, size - r * 1.2] }[b.pos];
      const cx = bx + (b.dx || 0) / 100 * size, cy = by + (b.dy || 0) / 100 * size;
      body.push(`<circle cx="${cx}" cy="${cy}" r="${r}" fill="${b.bg}"/>`);
      const dt = b.dotType || "none";
      if (dt === "icon") {
        const isz = r * 2 * 0.62;
        if (b.dotIconSvg) { // 在线 Iconify
          const vb = (b.dotIconVb || "0 0 24 24").split(/\s+/).map(Number);
          const ar = (vb[2] || 24) / (vb[3] || 24);
          const dw = ar >= 1 ? isz : isz * ar, dh = ar >= 1 ? isz / ar : isz;
          const inner = b.dotIconSvg.replace(/currentColor/g, b.fg);
          body.push(`<g transform="translate(${cx - dw / 2} ${cy - dh / 2}) scale(${dw / (vb[2] || 24)} ${dh / (vb[3] || 24)}) translate(${-(vb[0] || 0)} ${-(vb[1] || 0)})">${inner}</g>`);
        } else {
          const icon = BUILTIN_ICONS.find(i => i.n === b.dotIcon);
          if (icon) body.push(`<path transform="translate(${cx - isz / 2} ${cy - isz / 2}) scale(${isz / 24})" d="${icon.d}" fill="${b.fg}"${icon.fr ? ` fill-rule="${icon.fr}"` : ""}/>`);
        }
      } else if (dt === "emoji" && b.dotEmoji) {
        body.push(`<text x="${cx}" y="${cy + r * 0.06}" font-size="${r * 2 * 0.6}" text-anchor="middle" dominant-baseline="central">${esc(b.dotEmoji)}</text>`);
      } else if (dt === "image" && b.dotImage) {
        defs.push(`<clipPath id="dotclip"><circle cx="${cx}" cy="${cy}" r="${r * 0.92}"/></clipPath>`);
        body.push(`<image href="${b.dotImage}" x="${cx - r}" y="${cy - r}" width="${r * 2}" height="${r * 2}" preserveAspectRatio="xMidYMid slice" clip-path="url(#dotclip)"/>`);
      }
    } else { // ribbon
      const w = size * Math.SQRT2 * 0.42 * (b.size / 0.3);
      const fx = b.pos === "tl" || b.pos === "bl" ? -1 : 1;
      const fy = b.pos === "bl" || b.pos === "br" ? -1 : 1;
      const bh = fsz * 1.5;
      body.push(`<g transform="translate(${fx === 1 ? size : 0} ${fy === 1 ? 0 : size}) scale(${fx} ${fy}) rotate(45)"><rect x="${-w / 2}" y="${w * 0.28 - bh / 2}" width="${w}" height="${bh}" fill="${b.bg}"/><text x="0" y="${w * 0.28 + fsz * 0.04}" font-family="Inter,'Noto Sans SC',sans-serif" font-weight="800" font-size="${fsz}" fill="${b.fg}" text-anchor="middle" dominant-baseline="central">${esc(b.text)}</text></g>`);
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">${defs.length ? `<defs>${defs.join("")}</defs>` : ""}${body.join("")}</svg>`;
}

/* ── 导出文件清单（用于预览 + 实际生成）── */
function exportPlan() {
  const P = EXPORT_OPTS;
  const files = [];
  const add = (path, gen) => files.push({ path, gen });

  if (P.platforms.has("android")) {
    for (const [d, sz] of ANDROID_DENSITIES) {
      add(`android/mipmap-${d}/ic_launcher.png`, () => renderPng(sz, { shape: "rounded", radius: 18 }));
      add(`android/mipmap-${d}/ic_launcher_round.png`, () => renderPng(sz, { shape: "circle" }));
    }
    for (const [d, sz] of ANDROID_FG) {
      add(`android/mipmap-${d}/ic_launcher_foreground.png`, () => renderPng(sz, { bgOn: false, badgeOn: false, fgFactor: 2 / 3 }));
      add(`android/mipmap-${d}/ic_launcher_background.png`, () => renderPng(sz, { fgOn: false, badgeOn: false }));
      add(`android/mipmap-${d}/ic_launcher_monochrome.png`, () => renderPng(sz, { mono: "#ffffff", fgFactor: 2 / 3 }));
    }
    add("android/mipmap-anydpi-v26/ic_launcher.xml", () => adaptiveXml(true));
    add("android/mipmap-anydpi-v26/ic_launcher_round.xml", () => adaptiveXml(true));
    add("android/playstore-icon-512.png", () => renderPng(512, { shape: "square" }));
  }
  if (P.platforms.has("ios")) {
    for (const [fn, sz] of IOS_ICONS)
      add(`ios/AppIcon.appiconset/${fn}`, () => renderPng(sz, { shape: "square" }));
    add("ios/AppIcon.appiconset/Contents.json", () => iosContentsJson());
  }
  if (P.platforms.has("web")) {
    add("web/favicon.ico", async () => {
      const list = [];
      for (const sz of [16, 32, 48]) list.push({ size: sz, data: await renderPng(sz, webShape()) });
      return buildIco(list);
    });
    for (const sz of [16, 32, 96]) add(`web/favicon-${sz}x${sz}.png`, () => renderPng(sz, webShape()));
    add("web/apple-touch-icon.png", () => renderPng(180, { shape: "square" }));
    for (const sz of [192, 512]) add(`web/icon-${sz}x${sz}.png`, () => renderPng(sz, webShape()));
    add("web/icon-maskable-512x512.png", () => renderPng(512, { shape: "square" }));
    add("web/og-image.png", async () => {
      const cv = makeCanvas(1200, 630);
      await renderOg(cv.getContext("2d"), 1200, 630);
      return canvasToBytes(cv);
    });
    add("web/manifest.json", () => webManifest());
    add("web/snippet.html", () => webSnippet());
  }
  if (P.platforms.has("macos")) {
    add("macos/AppIcon.icns", async () => {
      const list = [];
      for (const sz of [16, 32, 64, 128, 256, 512, 1024])
        list.push({ size: sz, data: await renderPng(sz, { shape: "squircle", pad: 0.075 }) });
      return buildIcns(list);
    });
    for (const sz of [512, 1024])
      add(`macos/icon_${sz}x${sz}.png`, () => renderPng(sz, { shape: "squircle", pad: 0.075 }));
  }
  if (P.platforms.has("windows")) {
    add("windows/app.ico", async () => {
      const list = [];
      for (const sz of [16, 24, 32, 48, 64, 256]) list.push({ size: sz, data: await renderPng(sz, webShape()) });
      return buildIco(list);
    });
    for (const sz of [44, 71, 150, 310]) add(`windows/Square${sz}x${sz}Logo.png`, () => renderPng(sz, { shape: "square" }));
  }
  for (const sz of P.customSizes)
    add(`custom/icon-${sz}x${sz}.png`, () => renderPng(sz, webShape()));

  if (P.formats.has("webp"))
    for (const sz of [192, 512]) add(`extra/icon-${sz}.webp`, () => renderPng(sz, webShape(), "image/webp", 0.95));
  if (P.formats.has("svg"))
    add("extra/icon.svg", () => buildSvg(512));

  add("qm-icon-config.json", () => JSON.stringify(state, null, 2));
  add("README.md", () => readmeText());
  return files;
}

function readmeText() {
  if (LANG === "zh") return `# ${state.name} — 图标资源包

由 该影 icon 生成 · ${new Date().toLocaleString("zh-CN")}

## 目录说明
- android/ — 各密度 mipmap、自适应图标 XML（含 Android 13+ monochrome 主题层）、Play 商店 512
- ios/AppIcon.appiconset/ — 直接拖入 Xcode 的 Assets.xcassets 即可
- web/ — favicon.ico、PWA 图标、maskable、OG 社交图、manifest.json 与 HTML 片段
- macos/ — AppIcon.icns（Big Sur 风格圆角 + 留白）
- windows/ — app.ico（16~256 多尺寸）与磁贴 PNG
- custom/ — 你添加的自定义尺寸，例如 1024×1024、2048×2048
- qm-icon-config.json — 设计配置，可在 该影 icon 中重新导入继续编辑

## 使用提示
- iOS 图标按规范导出为全出血方形，系统会自动应用圆角遮罩
- Android 自适应图标前景层已按 108dp 安全区缩放
- 勾选 macOS 会包含 AppIcon.icns；勾选 Windows 会包含 app.ico
- App Store 图标固定包含 1024×1024；自定义尺寸会按输入的像素边长重新渲染，不是简单拉伸小图

## 关于
- 生成工具：该影 Icon Studio
`;
  return `# ${state.name} — Icon Assets

Generated by 该影 icon · ${new Date().toLocaleString("en")}

## Contents
- android/ — mipmap for every density, adaptive icon XML (incl. Android 13+ monochrome layer), Play Store 512
- ios/AppIcon.appiconset/ — drop straight into Xcode's Assets.xcassets
- web/ — favicon.ico, PWA icons, maskable, OG social image, manifest.json and HTML snippet
- macos/ — AppIcon.icns (Big Sur style rounded corners + margin)
- windows/ — app.ico (16–256 multi-size) and tile PNGs
- custom/ — your custom sizes, such as 1024×1024 or 2048×2048
- qm-icon-config.json — design config, re-import it in 该影 icon to keep editing

## Notes
- iOS icons are exported as full-bleed squares per spec; the OS applies the corner mask
- Android adaptive foreground layers are pre-scaled to the 108dp safe zone
- Selecting macOS includes AppIcon.icns; selecting Windows includes app.ico
- The App Store icon always includes 1024×1024; custom sizes are rendered at the requested pixel size instead of upscaling a small image

## About
- Tool: 该影 Icon Studio
`;
}

/* 文件树文本 */
function fileTreeText(files) {
  return files.map(f => f.path).join("\n");
}

/* 执行导出 */
async function runExport(onProgress) {
  const files = exportPlan();
  const zip = new ZipBuilder();
  for (let i = 0; i < files.length; i++) {
    const f = files[i];
    let data = await f.gen();
    zip.add(f.path, data);
    onProgress && onProgress((i + 1) / files.length, f.path);
  }
  const blob = zip.build();
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${(state.name || "icon").replace(/[^\w一-龥-]+/g, "-")}-icons.zip`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
  return files.length;
}
